project:
  type: website
  output-dir: docs
  resources:
    - "*.glb"

website:
  title: "Portfolio SIRI"
  navbar:
    background: "#121212"
    foreground: "#ffffff"
    left:
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true