project:
  type: website
  output-dir: docs
  resources:
    - "*.glb"

website:
  title: "Mon Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true