project:
  type: website
  output-dir: docs

website:
  title: "Mon Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: projects.qmd
        text: Projets

format:
  html:
    theme: dark
    toc: true